/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class PantallaIngreso extends javax.swing.JFrame {

    Vector vEstados = new Vector();
    private String[] simbolosEntrando;
    private String[] simbolos;
    private String[] estados;
    DefaultTableModel dtm;
    /**
     * Creates new form PantallaIngreso
     */
    public PantallaIngreso() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSimbolos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEstados = new javax.swing.JTextField();
        panelMostrador = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEstados = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        btnConversor = new javax.swing.JButton();
        btn_IngresarAutomata = new javax.swing.JButton();

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo2.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese los símbolos de entrada, separados por coma.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 107, 260, 40);
        getContentPane().add(txtSimbolos);
        txtSimbolos.setBounds(30, 160, 250, 24);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese los estados, seguidos por coma:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 230, 260, 16);
        getContentPane().add(txtEstados);
        txtEstados.setBounds(30, 260, 250, 24);

        panelMostrador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaEstados);

        panelMostrador.add(jScrollPane2);

        getContentPane().add(panelMostrador);
        panelMostrador.setBounds(330, 60, 450, 380);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(30, 320, 110, 32);

        btnConversor.setText("AFND a AF");
        btnConversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConversor);
        btnConversor.setBounds(150, 320, 130, 32);

        btn_IngresarAutomata.setText("Ingresar datos ");
        btn_IngresarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarAutomataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_IngresarAutomata);
        btn_IngresarAutomata.setBounds(490, 450, 200, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        simbolosEntrando = txtSimbolos.getText().split(",");
        simbolos = new String[simbolosEntrando.length + 2];
        simbolos[0] = "Estados";
        for (int sym = 1; sym < simbolos.length - 1; sym++) {
            simbolos[sym] = simbolosEntrando[sym - 1];
        }
        simbolos[simbolos.length - 1] = "E.A.";
        estados = txtEstados.getText().split(",");
        dtm = new DefaultTableModel(simbolos, 0);
        tablaEstados.setModel(dtm);
        for (int machete = 0; machete < estados.length; machete++) {
            String[] charles = new String[1];
            charles[0] = estados[machete];
            dtm.addRow(charles);
            vEstados.add(estados[machete]);
        }
        JOptionPane.showMessageDialog(rootPane, "Señor usuario, si desea operar con el automata finito (AF) \ntiene que llenar la tabla con las respectivas transiciones\ny luego hacer clic en el boton 'Operar'");
    }//GEN-LAST:event_btnIngresarActionPerformed
    
    private void btnConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConversorActionPerformed

    private void btn_IngresarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarAutomataActionPerformed
      matrizAutomata();
    }//GEN-LAST:event_btn_IngresarAutomataActionPerformed

    public int convertirEstados(String a){
        int valor=0;
        for(int i=0;i<estados.length;i++){
            if(estados[i].equals(a)){
                valor=i;
                
            }
        }
        return valor;
    }
    
    public int convertirSimbolos(String a){
        int valor=0;
        for(int i=0;i<simbolosEntrando.length;i++){
            if(simbolosEntrando[i].equals(a)){
                valor=i;
            }
        }
        return valor;
    }
    
    public int [][] matrizAutomata(){
        int[][] ma = new int[estados.length][simbolosEntrando.length];
        for (int i = 0; i < dtm.getRowCount() ; i++) {
            for (int j = 1; j < dtm.getColumnCount()-1; j++) {
                String estado = (String) dtm.getValueAt(i,0);
                if(estado!=null){
                    int numEstado = convertirEstados(estado);
                    ma[i][j]=numEstado;
                }else{
                    ma[i][j]=0;
                }
                System.out.println(ma[i][j]);
            }
        }
        return ma;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnConversor;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btn_IngresarAutomata;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelMostrador;
    private javax.swing.JTable tablaEstados;
    private javax.swing.JTextField txtEstados;
    private javax.swing.JTextField txtSimbolos;
    // End of variables declaration//GEN-END:variables
}
